# fly.toml app configuration file generated for eventz on 2024-12-13T04:21:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eventz'
primary_region = 'jnb'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
